# Basic info
title: Jabran Rafique
description: 'web developer, cartographer'
version: 0.0.2

# Routes
baseurl: /
# url: http://127.0.0.1:4000
url: http://jabranr.github.io
permalink: /:categories/:title/

# Pagination
paginate: 10

# Dependencies
markdown: redcarpet
pygments: true
