# Basic info
title: Jabran Rafique
description: 'web developer, cartographer'
version: 0.0.2

# Routes
url: http://127.0.0.1:4000
baseurl: /
permalink: /:categories/:title/

# Pagination
paginate: 10

# Dependencies
markdown: redcarpet
pygments: true
